### ISSUE TITLE
ComfyUI does support generic connections

### ISSUE THREAD

**Issue by Amorano** [rhdunn/comfyui-bus-plugin#3]
![image](https://github.com/user-attachments/assets/bf3a7f23-a111-447c-8f53-515f049390b9)

Sure it does. I have generic I/O's all over my nodes. 
AnyType by Pythongosssss directly uses the '*' any mechanism of Litegraph.

**Comment by rhdunn** [comment]
It doesn't propagate properly -- I've tried.

This is because the ComfyUI connector does the type propagation within JavaScript when evaluating the node graph, while the Python nodes are instantiated on specific types. Thus, you can't do e.g. `IMAGE -> AnyType -> IMAGE` as the final IMAGE has to have an image type.

See the comments in https://github.com/comfyanonymous/ComfyUI/issues/3851.

**Comment by Amorano** [comment]
> It doesn't propagate properly -- I've tried.
> 
> This is because the ComfyUI connector does the type propagation within JavaScript when evaluating the node graph, while the Python nodes are instantiated on specific types. Thus, you can't do e.g. `IMAGE -> AnyType -> IMAGE` as the final IMAGE has to have an image type.
> 
> See the comments in [comfyanonymous/ComfyUI#3851](https://github.com/comfyanonymous/ComfyUI/issues/3851).

Except I literally do that, all over:

![image](https://github.com/user-attachments/assets/ad3a5940-b12b-4572-99ee-13812710ee84)

unless I am misunderstanding something? Are you saying that you should be able to convert images into an "ANY" type in the graph? As an input, ANY TYPE exists and is easily cast-able to anything you want in python or javascript.

**Comment by rhdunn** [comment]
IIRC it breaks in several places:

1. using a ComfyUI Reroute node in-between the AnyNode and another node causes the reroute node to disconnect due to not being able to match the types;

2. binding an AnyNode to a primitive fails as the primitive can't infer the type as (unlike the reroute node) the actual type isn't propagated through the graph.

There may be other cases where it breaks; I didn't do extensive testing after running into those issues.

Regardless, I've found these nodes useful in other cases, e.g. using the parameters or prompts as a source to provide the inputs in a grouped collection.

**Comment by Amorano** [comment]
> IIRC it breaks in several places:
> 
>     1. using a ComfyUI Reroute node in-between the AnyNode and another node causes the reroute node to disconnect due to not being able to match the types;
> 
>     2. binding an AnyNode to a primitive fails as the primitive can't infer the type as (unlike the reroute node) the actual type isn't propagated through the graph.
> 
> 
> There may be other cases where it breaks; I didn't do extensive testing after running into those issues.
> 
> Regardless, I've found these nodes useful in other cases, e.g. using the parameters or prompts as a source to provide the inputs in a grouped collection.

1) That sounds more like a bug in the reroute node, which I think has a standing bug about that very problem.

2) How would it know what the now "ANYTYPE" is?  For example, if I sent in a Boolean to the ANYTYPE, is the output a BOOLEAN, INT or FLOAT?  There is no way to know without an explcit cast, hence why I added a SINGLE node that converts between most types:

![image](https://github.com/user-attachments/assets/a1cabef7-ca08-4872-8bf0-57527d961c79)

On that subject, if should the core be able to convert from one explicit type to another, yes. With registrations for users to extend it with their own types. Like any JSON parser.
